# Generated by Django 2.2.1 on 2019-06-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fire_date',
            field=models.DateField(blank=True),
        ),
    ]
