# Generated by Django 2.2.1 on 2019-06-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20190603_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
