# Generated by Django 2.2.1 on 2019-06-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeName',
        ),
    ]
